[build-system]
requires = ["uv_build>=0.12.17,<0.13"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["sgcc_wiki_backend"]
module-root = "src"

[project]
name = "sgcc-wiki-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.3",
    "bcrypt>=5.0.0",
    "diff-match-patch>=20241021",
    "fastapi>=0.128.8",
    "httpx>=0.28.1",
    "pyjwt>=2.14.0",
    "pyotp>=2.10.0",
    "python-dotenv>=1.2.1",
    "slowapi>=0.1.10",
    "sqlmodel>=0.0.34",
    "uvicorn[standard]>=0.39.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
